classify.py ad.tab bayes 0
classify.py ad.tab bayes 10
classify.py ad.tab bayes 20
classify.py ad.tab bayes 50
classify.py ad.tab bayes 100
classify.py ad.tab bayes 500
classify.py ad.tab svm 0
classify.py ad.tab svm 10
classify.py ad.tab svm 20
classify.py ad.tab svm 50
classify.py ad.tab svm 100
classify.py ad.tab svm 500